---
- name: Create keyring directory if it does not exist
  become: yes
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory

- name: Remove nodesource key
  become: yes
  ansible.builtin.file:
    path: /etc/apt/keyrings/nodesource.gpg
    state: absent

- name: Add nodesource key
  become: yes
  shell: "curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | gpg --dearmor -o /etc/apt/keyrings/nodesource.gpg"
  #apt_key:
  #  url: https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key
  #  file: /etc/apt/keyrings/nodesource.gpg
  #  state: present

- name: Build nodejs apt sources list
  become: yes
  apt_repository:
    repo: "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_20.x nodistro main"
    state: present
    filename: nodesource.list
    update_cache: yes

- name: Install nodejs		
  become: yes
  apt:
    name: 
    - nodejs
    update_cache: yes
    
- name: Install webUI
  become: yes
  shell: "curl -fsSL https://open5gs.org/open5gs/assets/webui/install | sudo -E bash -"
  
# echo "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_20.0 nodistro main" | sudo tee /etc/apt/sources.list.d/nodesource.list