---
- name: Install pip package
  when: ansible_distribution != "MacOSX"
  become: yes
  apt:
    update_cache: yes
    name: python3-pip

- name: Install docker, kubernetes and crypto python packages
  become: yes
  apt:
    name:
      - python3-docker
      - python3-kubernetes
      - python3-cryptography

- name: Install Helm Diff Plugin
  kubernetes.core.helm_plugin:
    plugin_path: https://github.com/databus23/helm-diff
