---
- name: Create a Magma Namespace
  kubernetes.core.k8s:
    name: "{{ magma_namespace }}"
    api_version: v1
    kind: Namespace
    state: present

- name: Delete agwc-secret-certs
  kubernetes.core.k8s:
    state: absent
    api_version: v1
    kind: Secret
    name: "agwc-secret-certs"
    namespace: "{{ magma_namespace }}"

- name: Create agwc-secret-certs
  shell:
    kubectl create secret generic agwc-secret-certs --from-file=rootCA.pem=/var/opt/magma/certs/rootCA.pem --namespace "{{ magma_namespace }}"
# Couldn't get the following to work
#  kubernetes.core.k8s:
#    state: present
#    namespace: "{{ magma_namespace }}"
#    definition: 
#      apiVersion: v1
#      kind: Secret
#      type: Opaque             
#      metadata:
#        name: "agwc-secret-certs"
#        namespace: "{{ magma_namespace }}"
#      dest: "/var/opt/magma/certs/rootCA.pem"
#      src: "/var/opt/magma/certs/rootCA.pem"   

- name: Configure the storage class
  kubernetes.core.k8s:
    state: present
    namespace: "{{ magma_namespace }}"
    src: "{{ helm_local }}/agwc/agwc-sc.yaml"
    
- name: Delete the persistent volume
  kubernetes.core.k8s:
    state: absent
    src: "{{ helm_local }}/agwc/agwc-pv.yaml"
    namespace: "{{ magma_namespace }}"

- name: Configure the persistent volume
  kubernetes.core.k8s:
    state: present
    src: "{{ helm_local }}/agwc/agwc-pv.yaml"
    namespace: "{{ magma_namespace }}"
    
- name: Deploy AGWC
  kubernetes.core.helm:
    name: agwc
    chart_ref: "{{ helm_local }}/agwc"
    create_namespace: true
    release_namespace: "{{ magma_namespace }}"
    state: "{{ agwc_state }}"
    values_files:
    - "{{ helm_local }}/agwc/values.yaml"


