---
all:
  # Update your VM or bare-metal IP address
  hosts: 192.168.1.220
  vars:
    ansible_user: "ubuntu"
    orc8r_domain: "galaxy.shubhamtatvamasi.com"
    # deploy_on_aws: true
    # deploy_domain_proxy: true
    # magma_docker_registry: "shubhamtatvamasi"
    # magma_docker_tag: "666a3f3"
    # orc8r_helm_repo: "https://shubhamtatvamasi.github.io/magma-charts-04-09-2023"
